name: Build Audio Plugins (Windows Only)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Reset CMake Cache (Remove build directory)
      shell: pwsh
      run: |
        if (Test-Path build) {
            Remove-Item -Recurse -Force build
        }

    - name: Configure CMake
      uses: lukka/get-cmake@latest

    - name: Set up MSVC (Windows)
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install WebView2 (Windows)
      shell: bash
      run: |
        nuget install Microsoft.Web.WebView2 -OutputDirectory "C:/webview2"

    - name: CMake Generate
      shell: bash
      run: |
        cmake -B build -G "Visual Studio 17 2022" -A x64 -DRNBO_EDITOR_MODE=WEBVIEW -DJUCE_WEBVIEW2_PACKAGE_LOCATION="C:/webview2" -DCMAKE_BUILD_TYPE=Release

    - name: CMake Build
      shell: bash
      run: |
        cmake --build build --config Release --parallel 2
        
    - name: Upload VST3 Artifact (Windows)
      uses: actions/upload-artifact@v4
      with:
        name: VST3-Windows
        path: build/RNBOAudioPlugin_artefacts/Release/VST3/
        
    - name: Upload Standalone App Artifact (Windows)
      uses: actions/upload-artifact@v4
      with:
        name: Standalone-App-Windows
        path: build/RNBOApp_artefacts/Release/